# Generated by Django 4.2.24 on 2025-09-16 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='Quantidade utilizada do produto', max_digits=5, verbose_name='Quantidade')),
                ('produto', models.ForeignKey(help_text='Nome do Produto', on_delete=django.db.models.deletion.PROTECT, related_name='produto', to='produtos.produto', verbose_name='Produto')),
                ('servico', models.ForeignKey(help_text='Nome do Serviço', on_delete=django.db.models.deletion.PROTECT, related_name='servico', to='servicos.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Produto Servico',
                'verbose_name_plural': 'Produtos Servicos',
            },
        ),
    ]
