# Generated by Django 5.2.5 on 2025-10-02 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_servico_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtosservico',
            name='servico',
            field=models.ForeignKey(help_text='Nome do Serviço', on_delete=django.db.models.deletion.CASCADE, related_name='servico', to='servicos.servico', verbose_name='Serviço'),
        ),
    ]
